### ISSUE TITLE
Offline dev- dns does not resolve correctly

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#1581]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/guides/offline-dev.html

**Describe the change you'd like**
I followed the instructions, and when I get to step 12 (lando start), I get the announcement that my site is available at mysite.test.

But when I actually try to go to mysite.test, I get a DNS not found error.  This happens both when I am online and offline.  However, mysite.lndo.site resolves normally. (Additional note: lando gulp breaks when I have "test.me" in `~/.lando/config.yml`).

Related issue: https://github.com/lando/lando/issues/448

Potential problem:

In step 10, it says to add "domain: test.me" to `~/.lando/config.yml`, and in step 12, it shows these results:

```
 APPSERVER URLS https://localhost:32791
                http://localhost:32792
                http://bestappever.test
                https://bestappever.test
```

But my actual results look like this (the .me) is still there:

```
 APPSERVER URLS https://localhost:32791
                http://localhost:32792
                http://bestappever.test.me
                https://bestappever.test.me
```

Also, in step 4, it says to configure`dnsmaqs.conf` like this:

`address=/test/127.0.0.1`

But some sources I checked online suggested it should be `.test` instead. (I don't have it working yet so I don't know what is correct, but as written the documentation currently does not appear to work on mojave (10.14.4)

**Comment by possiBri** [comment]
@ptmkenny the Test.me thing is a typo in the documentation. That final piece of updating the `~/.lando/config` file, if you just remove the ".me" from that declaration that should fix that piece of the issue, and that should get updated.

That being said, I just want to add that I'm on MacOS Mojave and I followed all of the instructions as well and I still have yet to get it to work. I used `*.lab` for my TLD, set up dnsmasq, added proper files/settings in all the config locations, and upon spin up they are still red and inaccessible. Now, if I `dig` or `ping` the domain I get success, but lando doesn't appear to be connecting somewhere. I've even tried changing `domain` to `proxyDomain` just to see (since that was the old naming convention) but that definitely didn't work. Additionally, I've found that even though they aren't listed in the spin up text, the `*.lndo.site` domains still work, in case that helps hunt down the issue. I've also tried just poking around in most of the different lando files just to see if maybe there was something missed, but I couldn't seem to find anything.

As always, thanks for an awesome product, because even with the little hiccups this is still worlds better than how I used to have to do local dev 👍

**Comment by possiBri** [comment]
UPDATE: I just did a `lando rebuild` which I could've sworn I'd tried at some point... but that totally fixed it. Upon restart everything is green and the page loads!

**Comment by dirtystylus** [comment]
Can confirm two things:

* Removing `.me` from the domain entry in **~/.lando/config.yml** helped
* `lando rebuild` was required, a simple `lando poweroff` and `lando start` did not work on two separate machines

Thanks @ptmkenny and @possiBri for documenting your attempts, your notes were super helpful.

**Comment by dirtystylus** [comment]
Also!

You need to make sure that your project domain with your TLD is in your **etc/hosts** file, or your URLs will still show up red after a `lando rebuild`. I’ve summarized my whole journey here: http://dirtystylus.com/2019/04/26/offline-development-with-lando/

**Comment by miiimooo** [comment]
@dirtystylus I'm going to read your blog post but a question: what about using dnsmasq? I think I had a working setup previously in linux with network-manager that didn't need an entry in /ect/hosts and just a wildcard dns entry in dnsmasq for .loc

**Comment by dirtystylus** [comment]
@miiimooo I can’t comment on the Linux side, but on the Mac OS side I had the `dnsmasq` entry for my TLD and it simply wouldn’t revolve without a an entry in `/etc/hosts`, for either my work or my home laptop. YMMV, as always

**Comment by pirog** [comment]
This documentation was provided quite awhile ago and i can confirm it is out of date on multiple fronts. The most pressing are the ones notes by @dirtystylus over at https://github.com/lando/lando/issues/1581#issuecomment-487180543

However, it's also worth pointing out that while you can straight up use a TLD we DO NOT recommend that you do so.
