### ISSUE TITLE
SIMPLETEST_BASE_URL doesn't seem to work with nginx

### ISSUE THREAD

**Issue by neclimdul** [lando/lando#2283]
Ran into a problem where I was having trouble running some tests in Drupal. Tracked down this stack exchange article.
https://stackoverflow.com/questions/56674749/failing-drupal-8-functional-tests-on-drupallogin

It seems like maybe this logic isn't correct
```
SIMPLETEST_BASE_URL: (options.via === 'nginx') ? 'https://appserver_nginx' : 'https://appserver',
```

I believe what is happening is that because traefik handles TLS/SSL termination and talks to nginx on port 80, nginx isn't generally listening on port 443 and then these tests that rely on SIMPLETEST_BASE_URL fail.

I'm not sure if this is also a problem with apache, But it seems like it might run into the same problem depending on the setup.

**Comment by pirog** [comment]
@neclimdul those are internal docker host names so traefik is not involved

**Comment by neclimdul** [comment]
Yeah, that was my point that it wasn't pointing to traefik. I think this probably happens when you want to do some custom config because setting up certificates is more difficult and you know self signed certs. I ran into this and wrote this up and worked around it real quick. I'll dig in more and see if can get a better reason someone might run into this but I was hoping maybe there was a quick fix.

**Comment by travis-bradbury** [comment]
> I'll dig in more and see if can get a better reason someone might run into this but I was hoping maybe there was a quick fix.

I run into the issue described in https://stackoverflow.com/questions/56674749/failing-drupal-8-functional-tests-on-drupallogin due to this. The tests check for successful login by looking up the session name. Because it thinks it's running under https, the name starts with `SSESS`. It fails to find a cookie by that name, so it thinks it isn't logged in. Printing HTML output during the tests makes it clear it had actually logged in.

It's actually using http (from appserver to appserver_nginx), so the correct name starts with `SESS`.

To work around it, I've been overriding SIMPLETEST_BASE_URL to `http://appserver_nginx` in .lando.yml.

**Comment by hkirsman** [comment]
I'm using nginx and getting

    GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to appserver port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

So it seems it doesn't switch to appserver_nginx at all.

I fixed it currently with force parameter in phpunit.xml and ran tests with 

    -c /app/phpunit.xml

    <env name="SIMPLETEST_BASE_URL" value="http://appserver_nginx" force="true"/>

**Comment by neclimdul** [comment]
it does switch to nginx but nginx doesn't list on on https so it ties out trying to talk to 443. your line works like the other fixes because its forcing drupal/phpunit to talk to http. I'll make a quick pull request for this.

**Comment by neclimdul** [comment]
So... as with many things it wasn't a quick pull. I believe there was legit a problem with nginx not listening on port 443 at some point but that doesn't seem to be the case anymore but it _is_ still broken just not as broken as I remember. The work around being discussed definitely works but _why_ it works is a bit complicated. Travis was on the right path with his comment about the session.

Here's _why_ the assertion is failing. When a functional tests logs in o,r does any similar action, Drupal ends up redirecting to the HTTP site because it doesn't _look_ like its running on HTTPS inside Drupal. That's where the assertion fails since Drupal logged the user into the http site but the test was expecting them to log into the https site. Its accidentally asserting a behavior of the environment not the site but i guess that's a fair assumption.

For some reason either the HTTPS identifier isn't being passed to Drupal from nginx or its not trusted and getting thrown away and that's at the root of the failure. I'll have to dig further but skipping the nginx template in lando it _seems_ like its just not going to be there. I expect https works from traefik because it provides the header out of the box and the protections you _might_ put in nginx to protect accepting that header aren't there because it trusts to always be behind traefik. 

It looks like it might be a bit of a tricky problem to fix correctly so the workaround is probably the best best in the short term for those of us running into it.

**Comment by xurizaemon** [comment]
I've observed this just recently, Lando v3.3.0. Using the http://appserver_nginx URL for SIMPLETEST_BASE_URL out of the box seems like a fairly harmless solution and nicer DX for those using the nginx server. Would there be disadvantages to changing it?

(Overriding via env_file didn't work for me, but the phpunit.xml force setting [here](https://github.com/lando/lando/issues/2283#issuecomment-758557622) did.)

**Comment by neclimdul** [comment]
ugh...
