### ISSUE TITLE
Issue with 3.20.7 debian package?

### ISSUE THREAD

**Issue by ericgsmith** [lando/lando#3642]
When updating to 3.20.7 I get a very odd experience.

Download https://github.com/lando/lando/releases/download/v3.20.7/lando-x64-v3.20.7.deb

```
sudo dpkg -i lando-x64-v3.20.7.deb
```

Then when I restart my terminal I get:

```
lando version
v3.21.0-alpha.7
```

And when I try to `lando start` by project I get:

```
ERROR ==> Could not find a service builder called drupal9 in the builder registry!
```

My colleague was able to reproduce the same issue trying to update to 3.20.7

I've never installed the alpha package listed, the tag diff looks normal to my eyes?

**Comment by ericgsmith** [comment]
https://github.com/lando/lando/compare/v3.20.6...v3.20.7 shows nothing of note - but the file size is 48.8MB for 3.20.6 and 36.1MB for 3.20.7

**Comment by anthropos9** [comment]
I'm seeing the same thing with Linux Mint.

**Comment by xurizaemon** [comment]
Seeing this on Ubuntu Jammy, downgrade to 3.20.6 fixed it for me.

**Comment by catgofire** [comment]
Same thing on Mac.

**Comment by catgofire** [comment]
Same thing on Mac
```sh
$ lando rebuild -y
WARN ==> wordpress is not a supported recipe type.
ERROR ==> Could not find a service builder called wordpress in the builder registry!

$ lando version
v3.21.0-alpha.7
```

**Comment by megclaypool** [comment]
Also on Mac:
$ lando version
v3.21.0-alpha.7   
   
`$ lando rebuild -y
WARN ==> pantheon is not a supported recipe type.
ERROR ==> Could not find a service builder called pantheon in the builder registry!`

**Comment by reynoldsalec** [comment]
Yeah recommend downgrading to v3.20.06; the CLI asset in that release was rolled against the wrong branch. Will be re-rolling a release against the correct branch shortly, apologies for the inconvenience.

**Comment by megclaypool** [comment]
Will you be providing install files for the new release? It looks like you re-rolled 3.20.7, and Lando is prompting me to upgrade, but all I see are source files 😛 I guess I *could* build it locally, but I'd rather not 😆

**Comment by reynoldsalec** [comment]
@megclaypool it takes about an hour between a release getting posted and the assets getting compiled...an annoying issue that will fortunately be going away in the next couple weeks when we release Lando 3.21.

For now, it looks like the newly posted 3.20.7 assets should be working, so I'm going to close this out!

**Comment by f1rf1n** [comment]
Also getting a recipe drupal7 unknown. Hopefully that is not really getting removed (for at least a year)

**Comment by edurenye** [comment]
Just downloaded the package and I'm getting the error:
`drupal10 is not a supported recipe type.`

**Comment by xurizaemon** [comment]
Yep, confirmed for me @reynoldsalec, downloaded a fresh copy just now and the .deb is still showing the same behaviours.

```
$ md5sum lando-x64-v3.20.7.deb 
e674425b957f8219d37a1fddc48c02da  lando-x64-v3.20.7.deb
```

```
$ lando version
v3.21.0-alpha.7
```

```
$ lando info
WARN ==> drupal10 is not a supported recipe type.
ERROR ==> Could not find a service builder called drupal10 in the builder registry!
```

Freshly downloaded, made sure to bypass any possible caches my side.

**Comment by pirog** [comment]
not sure what is going on here so i removed 3.20.7 from both the cli and package installer releases. please downgrade to 3.20.6 until we figure out what is going on

**Comment by reynoldsalec** [comment]
Re-rolled a 3.20.8 to make sure no incorrect cached resources are getting pulled in; sounds like that is working for folks: https://github.com/lando/lando/releases/tag/v3.20.8

**Comment by ericgsmith** [comment]
Thanks @reynoldsalec 

3.20.8 working for me :+1: 

```
lando version
v3.20.8
```

**Comment by anthropos9** [comment]
Working correctly for me on Linux Mint 21.2. Thanks to everyone involved.

**Comment by edurenye** [comment]
Working correctly for me too. Thank you!

**Comment by josebc** [comment]
try running `lando plugin-add @lando/drupal`
